Mdc json field converters
logfellow/logstash-logback-encoder pull request #957
Opened 2023-05-19 10:47 UTC by jug

Solution proposal for issue https://github.com/logfellow/logstash-logback-encoder/issues/955

2023-06-17 18:03 UTC, philsttr requested changes
Thanks for the contribution!   I really like the approach you came up with.  I have some feedback on naming and some low level implementation details.  But in general, the design is solid.

2023-06-18 06:35 UTC, jug commented on src/main/java/net/logstash/logback/composite/loggingevent/mdc/BooleanMdcFieldConverter.java
> +        return false;
yes, that works too (and is simpler).

2023-06-18 07:27 UTC, jug commented on src/main/java/net/logstash/logback/composite/loggingevent/mdc/LongMdcFieldConverter.java
> +        return false;
I've originally used the parsing right away as I don't need to know what makes a Long or Double and the try-catch is needed regardless ... a number greater Long.MAX_VALUE looks like a number, but cannot be parsed into a Long.

But I agree that lots of Exceptions are catched.
Will add a preliminary check.

2023-06-18 07:34 UTC, jug commented on src/main/java/net/logstash/logback/composite/loggingevent/mdc/MdcField.java
> +    public MdcField(String name, String alternateName, String value) {
I was also not keen on the name `alternateName`, but didn't quite wrap my head around for something more speaking.
 
will do

2023-06-18 07:45 UTC, jug commented on src/main/java/net/logstash/logback/composite/loggingevent/mdc/DoubleMdcFieldConverter.java
> +        }
ok ... will add check

2023-06-18 07:57 UTC, jug commented on src/main/java/net/logstash/logback/composite/loggingevent/mdc/MdcFieldConverter.java
> +public interface MdcFieldConverter {
makes sense ... will rename

2023-06-18 09:22 UTC, jug commented on src/main/java/net/logstash/logback/composite/loggingevent/mdc/MdcField.java
> +public class MdcField {
make sense ... will remove

2023-06-18 09:23 UTC, jug commented on src/main/java/net/logstash/logback/composite/loggingevent/mdc/MdcFieldConverter.java
> +    boolean writeMdcField(JsonGenerator generator, MdcField mdcField) throws IOException;
come by on refactoring for the other changes anyway

2023-06-18 12:37 UTC, philsttr approved these changes

2023-06-18 12:38 UTC, merged

2023-06-18 12:39 UTC, philsttr commented
Thanks for the quick turnaround on my review comments!  This will be included in the next release (soon)